### ISSUE TITLE
Strange Behavior

### ISSUE THREAD

**Issue by kingphantom** [superolmo/BigFiles#10]
Used notepad++ to download this plugin and started to get strange behavior.

**----------------------------------------**

**~** Double click of the left mouse button only opened the "properties" window of anything attempted in running or to open/view.

**~** Right click menu would not open

**~** Pressing the "windows" button did nothing. Only clicking the icon would give a response.
Attempting to type in the windows menu would give no response from the keyboard.

**~** Machine failed to boot on restart. Could not access safe mode. Had to repair the pc from disc.

**----------------------------------------**

No issues existed prior to this being installed. The machine is currently identical prior to repair just without the plugin. 

This is something to further look into especially if it is somehow corrupting the boot partition. 

OS: Windows 7
NP++ Version (x86)

**Comment by superolmo** [comment]
That is some major issue considering that the plugin does not write to disk.
Let's see, you are on 32 bit Windows 7, and assuming that you have not looked online for other answers.
The first and second issue that you mentioned I get them sometime when the ALT keys is stuck. See this "In Windows, holding ALT and double-clicking a drive or folder opens its properties" from [social.technet.microsoft.com/Forums](https://social.technet.microsoft.com/Forums/windows/en-US/d8533a8a-d047-41d9-a264-ff93a3bbb680/double-click-a-drive-or-folder-opens-the-properties-dialog-instead-of-the-normal-open-behavior?forum=w7itproui)

If you believe that the problem is due to Notepadd++ with Bigfiles plugins, I would need to make sure that the problem is repeatable. If you have not yet tryed, I suggest you to Sandbox the application using one of the methods address in the following website [4 Free Tools to Sandbox Programs and Keep Your Computer Safer](https://www.raymond.cc/blog/no-more-worries-when-running-untrusted-programs/). My preference is Sandboxie at [https://www.sandboxie.com/](https://www.sandboxie.com/)

Let me know if you can find if the issue is repeatable for me so I can test for it.
